### ISSUE TITLE
ImportError: cannot import name 'common' from 'kafka'

### ISSUE THREAD

**Issue by Jayesh-Popat** [wbarnha/kafka-python-ng#185]
>>> from kafka import KafkaConsumer
>>> from kafka import common
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'common' from 'kafka' (/usr/local/lib/python3.11/dist-packages/kafka/__init__.py)
>>>

python version used 3.11

`root@jack:~# python3.11 -m pip list | grep kafka `
`kafka-python-ng     2.2.2 `
`root@jack:~#`

**Comment by wbarnha** [comment]
I'm a bit confused as to what's going on here. https://github.com/wbarnha/kafka-python-ng/blob/448017ecad1b058d2f6f14f13c4f733183272479/docs/changelog.rst#core--protocol specifies that `kafka.common` shouldn't be getting used, and I do not see any references to `common` in the code anymore [since it was removed after v0.9.5](https://github.com/dpkp/kafka-python/blob/v0.9.5/kafka/common.py). Could you provide an example as to what you're trying to run?
